services:
    instant_job_db:
        image: postgres
        restart: always
        environment:
            - POSTGRES_USER=instantjob
            - POSTGRES_PASSWORD=instantjob
            - POSTGRES_DB=instantjob
        container_name: "instantjobdb"
        ports:
            - "5432:5432"